"""Explicit optional checks in the source-offline profile.

These exclusions are visible in source.json and do not qualify their features.
A different skip reason, or any new skipped test, fails the profile. OpenPI/JAX,
LanA data, and external maintainer scripts require separate qualification.
"""

OPTIONAL_SKIPS = {
    'unified': {
        'tests/test_openpi_instrumentation.py': 'Set OPENPI_SOURCE for optional OpenPI/JAX qualification',
        'tests/test_root_hygiene.py': 'root-hygiene checker is a maintainer tool, not part of the package',
        'tests/test_algonauts_heldout.py::TestWriteSubmissionZip::test_zip_contains_single_nested_npy': 'submission bundler is a local operational driver, not part of the package',
        'tests/test_algonauts_heldout.py::TestWriteSubmissionZip::test_ood_split_uses_ood_npy_name': 'submission bundler is a local operational driver, not part of the package',
        'tests/test_algonauts_heldout.py::TestWriteSubmissionZip::test_unknown_split_raises': 'submission bundler is a local operational driver, not part of the package',
        'tests/test_algonauts_heldout.py::TestWriteSubmissionZip::test_wrong_parcel_count_raises': 'submission bundler is a local operational driver, not part of the package',
        'tests/test_algonauts_heldout.py::TestWriteSubmissionZip::test_empty_episode_dict_raises': 'submission bundler is a local operational driver, not part of the package',
        'tests/test_algonauts_heldout.py::TestBuildSubmission::test_assembles_subjects_into_nested_zip': 'submission bundler is a local operational driver, not part of the package',
        'tests/test_algonauts_heldout.py::TestBuildSubmission::test_missing_subject_raises': 'submission bundler is a local operational driver, not part of the package',
        'tests/test_algonauts_heldout.py::TestBuildSubmission::test_wrong_parcel_count_raises': 'submission bundler is a local operational driver, not part of the package',
        'tests/test_lebel2023_language_mask.py::TestAgainstTheAtlas::test_mask_holds_the_requested_share_of_cortex': 'LanA atlas not present; set BRAINSCORE_LANA_ATLAS (osf.io/kzwbh)',
        'tests/test_lebel2023_language_mask.py::TestAgainstTheAtlas::test_mask_is_left_lateralised': 'LanA atlas not present; set BRAINSCORE_LANA_ATLAS (osf.io/kzwbh)',
        'tests/test_lebel2023_language_mask.py::TestAgainstTheAtlas::test_probabilities_are_a_probability': 'LanA atlas not present; set BRAINSCORE_LANA_ATLAS (osf.io/kzwbh)',
        'tests/test_lebel2023_language_mask.py::TestAgainstTheAtlas::test_downsampling_takes_the_leading_ico5_block': 'LanA atlas not present; set BRAINSCORE_LANA_ATLAS (osf.io/kzwbh)',
        'tests/test_lebel2023_language_mask.py::TestLanguageMaskVariant::test_variant_reports_the_masked_mean': 'LanA atlas not present; set BRAINSCORE_LANA_ATLAS (osf.io/kzwbh)',
        'tests/test_libero_transport.py::test_reference_and_umi_over_real_websocket_with_record_replay': 'Requires pinned OpenPI source',
        'tests/test_openpi_remote.py::test_loopback_record_ablate_ack_and_cleanup': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_disconnect_during_inference_cleans_before_next_request': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_record_budget_failure_removes_hooks': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_mismatched_response_closes_client': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_missing_configuration_ack_closes_client': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_client_callback_failure_cleans_scopes': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_server_serializes_clients': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-Mismatched operation]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-policy failed]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-Malformed inference0]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-Malformed inference1]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-Unexpected activity scope0]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-Unexpected activity scope1]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-Unexpected activity scope2]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-does not match0]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-does not match1]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_reply_closes_connection_without_delivering_activity[<lambda>-does not match2]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_all_activity_is_validated_before_any_callback': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_activity_cannot_be_delivered_to_an_ablation_scope': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_server_reports_policy_failure_and_next_client_is_unmodified': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_text_request_is_rejected_without_poisoning_connection': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_client_rejects_foreign_thread_without_sending_request': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_invalid_provider_setup_leaves_client_usable': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_unsupported_server_handshake_closes_connection': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_oversized_response_cleans_tools_before_reporting_error': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_detach_failure_preserves_original_error_and_clears_scope[False]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
        'tests/test_openpi_remote.py::test_detach_failure_preserves_original_error_and_clears_scope[True]': "could not import 'openpi_client.msgpack_numpy': No module named 'openpi_client'",
    },
}
